const {
	MOTE_RATE,
	CSPR_TRANSFER_FEE,
	CSPR_AUCTION_DELEGATE_FEE,
	CSPR_AUCTION_UNDELEGATE_FEE,
	TOKEN_TRANSFER_FEE,
	IPFS_GATEWAY,
} = require('../../constants');

module.exports = {
	get: async (req, res) => {
		res.json({
			MOTE_RATE,
			API_VERSION: '1.0.1',
			CSPR_TRANSFER_FEE,
			CSPR_AUCTION_DELEGATE_FEE,
			CSPR_AUCTION_UNDELEGATE_FEE,
			TOKEN_TRANSFER_FEE,
			IPFS_GATEWAY,
		});
	},
};
