# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages and test
      run: |
        yarn
        yarn run test-ci
      env:
        CI: true
         
  notification:

      needs: [deploy]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Send build result to slack channel
          uses: rtCamp/action-slack-notify@v2
          env: 
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_COLOR: ${{ job.status }}
            SLACK_FOOTER: Powered by CasperDash
